GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2FyYW4iLCJpYXQiOjE2MzExMzI0MjN9.Ii-oHXe4OCUYeeWOXy7OsJRuMTtgNuGgu3aPLslbh9o 
###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Sahil"
}